SELECT products.products_ID, products.USER_ID, products_NAME, DESCRIPTION, VENDOR_LINK, VALID_UNTIL, DISCOUNT, CREATED_AT, PHOTO_LINK, REWIEWS_RATINGS.AVG_RATING FROM discount.products
LEFT JOIN (SELECT REVIEWS.products_ID, AVG(REVIEWS.RATING) AVG_RATING FROM REVIEWS
GROUP BY REVIEWS.products_ID) AS REWIEWS_RATINGS
ON products.products_ID = REVIEWS_RATINGS.products_ID
WHERE AVG_RATING > 3