SELECT products_ID, products.USER_ID, USERNAME, products_NAME, DESCRIPTION, VENDOR_LINK, VALID_UNTIL, DISCOUNT, CREATED_AT, PHOTO_LINK FROM discount.products
LEFT JOIN(SELECT USERNAME, USER_ID FROM discount.user) as USER
ON products.USER_ID = USER.USER_ID
WHERE USERNAME = 'Alex' AND date(CREATED_AT) = '2021-03-01'