SELECT USER_ID, USERNAME FROM 
(SELECT USER.USER_ID, USERNAME, ISVENDOR, count(USER.USER_ID) products_AMOUNT FROM discount.products 
LEFT JOIN discount.USER 
ON products.USER_ID = USER.USER_ID
WHERE VALID_UNTIL >= curdate()
GROUP BY USER_ID) AS products_FOR_USER
WHERE OFFER_AMOUNT > 3